### ISSUE TITLE
Mana pool is off

### ISSUE THREAD

**Issue by vesperae** [further-reading/Dicecord#2]
The numbers for the mana pools seem off from the rulebook - Creating a new character sheet has the pool at 6 for Gnosis 1, but the mana pool at Gnosis 1 is 10.

The numbers you seem to have are 6/7/8/9/10/20/30/40/50/75 for Gnosis 1-10, but they should be: 10/11/12/13/15/20/25/30/50/75

**Comment by further-reading** [comment]
Thanks for the report. Just fixed the code now, will be included in the 1.01 update, launching this week. :)
